storage:
  id: storageManager
  scan:
    package: com.richguy.resource
  resource:
    location: classpath:/excel
    suffix: xlsx

weChat:
  webhook: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=xxxxxxxxxxxx


juhe:
  stockUrl: http://web.juhe.cn:8080/finance/stock/hs?gid={}&key=yourkey
  topNewsUrl: http://v.juhe.cn/toutiao/index?type=top&key=yourkey
  guojiNewsUrl: http://v.juhe.cn/toutiao/index?type=guoji&key=yourkey
  kejiNewsUrl: http://v.juhe.cn/toutiao/index?type=keji&key=yourkey
  newsUrl: http://v.juhe.cn/toutiao/content?uniquekey={}&key=yourkey
