storage:
  id: storageManager
  scan:
    package: com.richguy.resource
  resource:
    location: classpath:/excel
    suffix: xlsx

weChat:
  webhook: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=818aa476-e0db-4346-a68f-efbac919b371

qq:
  qqIds: 123456789
  password: abcabc
  pushGroupIds: 123456789, 123456789

juhe:
  stockUrl: http://web.juhe.cn:8080/finance/stock/hs?gid={}&key=yourkey
  topNewsUrl: http://v.juhe.cn/toutiao/index?type=top&key=yourkey
  guojiNewsUrl: http://v.juhe.cn/toutiao/index?type=guoji&key=yourkey
  kejiNewsUrl: http://v.juhe.cn/toutiao/index?type=keji&key=yourkey
  newsUrl: http://v.juhe.cn/toutiao/content?uniquekey={}&key=yourkey
