storage:
  id: storageManager
  scan:
    package: com.richguy.resource
  resource:
    location: classpath:/excel
    suffix: xlsx

qq:
  qqId: 123456789
  password: abcabc
  pushGroupIds: 123456789, 123456789